name: Procurement workflow

on:
  push:
    branches: [prod]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Production Code
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: cd procurement
      - run: npm install
      - run: npm run build --if-present
      - run: cp -r build/* var/www/procurement
